cookie:
  name: beu_dashboard_cookie
  key: a_long_random_signature_string_123
  expiry_days: 30
credentials:
  usernames:
    biniyam0928@gmail.com:
      email: biniyam0928@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Biniyam
      last_name: Girma
      logged_in: True # Will be managed automatically
      password: '091625' # Will be hashed automatically
      roles: # Optional
      - admin
      - editor
      - viewer
    mosesteshomework@gmail.com:
      email: mosesteshomework@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Moses
      last_name: Teshome
      logged_in: False # Will be managed automatically
      password: admin123 # Will be hashed automatically
      roles: # Optional
      - admin
      - editor
      - viewer
    abeyimentesnot543@gmail.com:
      email: abeyimentesnot543@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Mintesnot
      last_name: Abeyie
      logged_in: False # Will be managed automatically
      password: admin111 # Will be hashed automatically
      roles: # Optional
      - admin
      - Team 2
      - editor
    data@et.beudelivery.com:
          email: data@et.beudelivery.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: Data
          last_name: Team
          logged_in: False # Will be managed automatically
          password: admin112 # Will be hashed automatically
          roles: # Optional
          - admin
          - editor
          - viewer
    messihi1234@gmail.com:
          email: messihi1234@gmail.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: Messi
          last_name: Haile
          logged_in: False # Will be managed automatically
          password: Mes1919Mes@ # Will be hashed automatically
          roles: # Optional
          - admin
          - Team 1
          - editor
    kaluaabe@gmail.com:
          email: kaluaabe@gmail.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: Kalewengel
          last_name: Abebe
          logged_in: True 
          password: '121314' 
          roles: # Optional
          - admin
          - editor
          - viewer
    bdmanager@et.beudelivery.com:
          email: bdmanager@et.beudelivery.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: BD 
          last_name: Manager
          logged_in: True 
          password: Besisay@12345678 
          roles: # Optional
          - admin
          - editor
          - viewer
    test@gmail.com:
          email: test.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: Abreham 
          last_name: Sileshi
          logged_in: False 
          password: "1234"
          roles: # Optional
          - viewer
    mebafikadu706@gmail.com:
          email: mebafikadu706@gmail.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: Harwgeweyn 
          last_name: " "
          logged_in: False 
          password: "g5vrUxRxN130QsJF"
          roles: # Optional
          - viewer
    abelwasihun4@gmail.com:
          email: abelwasihun4@gmail.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: Abel 
          last_name: "Wassihun"
          logged_in: False 
          password: "YqUqqG04pZ77HpPA"
          roles: # Optional
          - viewer
    Rekikmistir1@gmail.com:
          email: Rekikmistir1@gmail.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: Rekik 
          last_name: " "
          logged_in: False 
          password: "MrzcCEfrBgnNbMQG"
          roles: # Optional
          - viewer
    Yeabtsegaayele81@gmail.com:
          email: Yeabtsegaayele81@gmail.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: Yeabtsega 
          last_name: " "
          logged_in: False 
          password: "c2aaZGicyrhQxX8U"
          roles: # Optional
          - viewer