cookie:
  name: beu_dashboard_cookie
  key: a_long_random_signature_string_123
  expiry_days: 30
credentials:
  usernames:
    biniyam0928@gmail.com:
      email: biniyam0928@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Biniyam
      last_name: Girma
      logged_in: True # Will be managed automatically
      password: '$2b$12$XLry206LNG8.wi.WQsZBpeK6fAqkRBAukhbE6Y/oHb/Omadaf9ywq' # Will be hashed automatically
      roles: # Optional
      - admin
      - editor
      - viewer
    mosesteshomework@gmail.com:
      email: mosesteshomework@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Moses
      last_name: Teshome
      logged_in: False # Will be managed automatically
      password: '$2b$12$MbX1oQdZ7JQnTb4LDsiKu.jKP../1IpSCyoy7ZztqF71wBpl.Gsgy' # Will be hashed automatically
      roles: # Optional
      - admin
      - editor
      - viewer
    abeyimentesnot543@gmail.com:
      email: abeyimentesnot543@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Mintesnot
      last_name: Abeyie
      logged_in: False # Will be managed automatically
      password: '$2b$12$n4n9k84Ra8qUQsbhhiUZb.hzCAscdBOAFQeVHjLRCxIE.CVAZNfm.' # Will be hashed automatically
      roles: # Optional
      - admin
      - Team 2
      - editor
    data@et.beudelivery.com:
          email: data@et.beudelivery.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: Data
          last_name: Team
          logged_in: False # Will be managed automatically
          password: '$2b$12$vj.3xTIjuG0WK7DgWNE5nOW6/f/pYPKH2OZ91PnWhhzNs6Leq0x4C' # Will be hashed automatically
          roles: # Optional
          - admin
          - editor
          - viewer
    messihi1234@gmail.com:
          email: messihi1234@gmail.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: Messi
          last_name: Haile
          logged_in: False # Will be managed automatically
          password: '$2b$12$V8Hnl4a2lr5qTk5MhhD1dOPSvScTNsJbxKbPxN2FkVg/EsmtL/DC.' # Will be hashed automatically
          roles: # Optional
          - admin
          - Team 1
          - editor
    kaluaabe@gmail.com:
          email: kaluaabe@gmail.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: Kalewengel
          last_name: Abebe
          logged_in: True 
          password: '$2b$12$V5MpF9l5Ht5x/bxZyKS7tOd3vB48u92wEbKfehx0aQg6xcc4hZBSq' 
          roles: # Optional
          - admin
          - editor
          - viewer
    bdmanager@et.beudelivery.com:
          email: bdmanager@et.beudelivery.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: BD 
          last_name: Manager
          logged_in: True 
          password: '$2b$12$F08WeZIn4rhWa2vXmMJKGec1UfPRxg2l6CK3azY6Ok6putB0gWbCq' 
          roles: # Optional
          - admin
          - editor
          - viewer
    test@gmail.com:
          email: test.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: Abreham 
          last_name: Sileshi
          logged_in: False 
          password: "$2b$12$9QDQ6oOyE2nMKodTpVTY7e8pNycfFqCKHWEEt1PkmdMiCcoWfEv2O"
          roles: # Optional
          - viewer
    abelwasihun4@gmail.com:
          email: abelwasihun4@gmail.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: "Abel"  
          last_name: "Wasihun"
          logged_in: False 
          password: "$2b$12$op3PZ.khDswlMenIPTOtv.EyV91TOWhvmbMTZY1XKhZ6cZT2QSMqe"
          roles: # Optional
          - viewer
    Rekikmistir1@gmail.com:
          email: Rekikmistir1@gmail.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: "Rekik"  
          last_name: "Mistir"
          logged_in: False 
          password: "$2b$12$SeNjoIfReq//nJ5EapV3CeNbsJuCiC2Qwjp1n8a8Z3WNCaqjynE9."
          roles: # Optional
          - viewer
    Yeabtsegaayele81@gmail.com:
          email: Yeabtsegaayele81@gmail.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: "Yeabtsega" 
          last_name: "Ayele"
          logged_in: False 
          password: "$2b$12$j3HzSoTAiGvb1bZnHD.AnOMqFo1hD0I20CM55dDAaj4UjI1JJLtsC"
          roles: # Optional
          - viewer
    yohannesgirmay6@gmail.com:
          email: yohannesgirmay6@gmail.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: "Yohannes"  
          last_name: "Girmay"
          logged_in: False 
          password: "$2b$12$/HUWxje70LozCVzdLWZT0.5AzC8gjN9bejL/IX4kSXKX72fQk8KRq"
          roles: # Optional
          - viewer
    abrehamsileshi6@gmail.com:
          email: abrehamsileshi6@gmail.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: "Abreham"  
          last_name: "Sileshi"
          logged_in: False 
          password: "$2b$12$YdxS/bNh977lGyHvJML5aeCBUZI7XuA24LdPedTyXXnbvw0178w/6"
          roles: # Optional
          - viewer
    cherenetsolomon70@gmail.com:
          email: cherenetsolomon70@gmail.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: "Chernet" 
          last_name: "Solomon"
          logged_in: False 
          password: "$2b$12$4KBQqYo./uFnYZtskjDLaeUJA1YQ4VpRElwemP8VZcr0dumOYztf6"
          roles: # Optional
          - viewer
    mebafikadu706@gmail.com:
          email: mebafikadu706@gmail.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: "Haregewyn" 
          last_name: "Fikadu"
          logged_in: False 
          password: "$2b$12$cdV99LgZX.UOkWifus86u.Mkodi8u7QjA1nhjjHhYFyxb346BoRZW"
          roles: # Optional
          - viewer
    Kedirmifta3@gmail.com:
          email: Kedirmifta3@gmail.com
          failed_login_attempts: 0 # Will be managed automatically
          first_name: "Mifta" 
          last_name: "Kedir"
          logged_in: False 
          password: "$2b$12$8pW6gFAcuDdbU.Rfm8PXouZ.6XM78AoNwttS9cq/sht9lHtAMYc/2"
          roles: # Optional
          - viewer